# Plugins
# Examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# prefix + I: Install new plugins
# prefix + U: Update plugins
# prefix + alt + u: Remove/uninstall plugins not on the list

# List of plugins (alternative definition for custom config files)
set -g @tpm_plugins '          \
  tmux-plugins/tpm             \
  tmux-plugins/tmux-sensible   \
  tmux-plugins/tmux-resurrect  \
  tmux-plugins/tmux-continuum  \
'

# Tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Basic tmux settings
set -g @plugin 'tmux-plugins/tmux-sensible'

# Save/restore sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'